service: whatsapp-bot

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    VERIFY_TOKEN: "clemente"
    FB_APP_ID: 3795354010703457
    FB_APP_SECRET: "6602daa9fb345e976562f6f032a0280"
    SECRET_NAME: "whatsapp_token"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:DescribeSecret"
            - "secretsmanager:PutSecretValue"  # Añadido para permitir la actualización del secreto
          Resource: "arn:aws:secretsmanager:us-east-1:992382408780:secret:whatsapp_token-*"

functions:
  webhook:
    handler: dist/handler.handler
    events:
      - http:
          path: /webhook
          method: ANY
          cors: true

  refreshTokenJob:
    handler: dist/handler.refreshWhatsAppToken
    events:
      - schedule: rate(55 days)  # Ejecuta la función cada 55 días para renovar el token

plugins:
  - serverless-offline
