service: whatsapp-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    VERIFY_TOKEN: "clemente"
    WHATSAPP_TOKEN: "EAA172rea1mEBO0vr9nGljmPpkpinqm8K9pzbjhAZCezEX4XB09VUVzTE7grRSCTBCr2rNZBAc9LSkINIaTZAY1s2PZAQLpVywXz18PX07WK0sbn7XZAB7G4T9wqFy5Ee82F6MGGJxMJwPTn51XqOWYWcemj0CtT9jcEskwRkXe7dzZA4mNbVsrp0wyZC7trBdopmZCthbouv6Uq8pBpO0d6QidxGiZCtGAT0rNq0ZD"

functions:
  webhook:
    handler: dist/handler.handler
    events:
      - http:
          path: /webhook
          method: ANY   # Cambiado a ANY para aceptar GET y POST
          cors: true

plugins:
  - serverless-offline
